class Constants:

    TOTAL_CARDS = 104
    ROWS = 4
    COLUMNS = 5
    MIN_PLAYERS = 2
    MAX_PLAYERS_PER_ROOM = 10
    MAX_PLAYERS_IN_GAME = 50
    CARDS_PER_HAND = 10
    MAX_PENALTY_POINTS = 66
    CLEAR_SCREEN = "\033[2J\033[H"
    CARD_HEIGHT = 4
    CARD_WIDTH = 9
